security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        oauth_token:
                pattern: ^/oauth/v2/token
                security: false
        api:
               pattern: ^/api/v1
               fos_oauth: true
               stateless: true
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                success_handler: authentication_handler
                failure_handler: authentication_handler
                csrf_provider: form.csrf_provider
                remember_me:  true
                always_use_default_target_path : true
                default_target_path: /account/dashboard
                use_referer : true
                use_forward:
            oauth:
                resource_owners:
                    google:             /login/check-google
                login_path:       /login
                success_handler: authentication_handler
                remember_me:     true
                failure_handler: authentication_handler
                oauth_user_provider:
                    service: google_user_provider
            logout:
                path:           /logout
                target:         /login
                success_handler: authentication_handler.logout_success_handler
            anonymous:    true
            remember_me:
                key:     "%secret%"
                lifetime: 31536000 # 365 days in seconds

    access_control:
        - { path: ^/oauth/v2/token, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/check-google, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/create, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/activation, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/user_acccept_invitation, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/user_reject_invitation, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/finance/export/csv, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/finance/export/time/csv, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/account, roles: ROLE_USER}
        - { path: ^/uploads/files$, roles: ROLE_USER}
        - { path: ^/api/doc, roles: ROLE_USER}
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
