<?php

namespace  WWSC\ThalamusBundle\Repository;

/**
 * ClientRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApiClient()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->setMaxResults( 1 );
        $qb->orderBy('c.id', 'DESC');

        return $qb->getQuery()->getSingleResult();
    }
}
